public class TreeGenerator {
    public String generate_tree_1(){
        return
                """
                                                    
                                                    CREATE\s
                                                      (A:TypeC {name: 'A'}),
                                                      (B:TypeC {name: 'B'}),
                                                      (C:TypeC {name: 'C'}),
                                                      (D:TypeC {name: 'D'}),
                                                      (E:TypeC {name: 'E'}),
                                                      (F1:TypeC {name: 'F1'}),
                                                      (F2:TypeC {name: 'F2'}),
                                                      (F3:TypeC {name: 'F3'}),
                                                      (F4:TypeC {name: 'F4'}),
                                                      (F5:TypeC {name: 'F5'}),
                                                      (F6:TypeC {name: 'F6'}),
                                                      (F7:TypeC {name: 'F7'}),
                                                      (F8:TypeC {name: 'F8'}),
                                                      (F9:TypeC {name: 'F9'}),
                                                      (F10:TypeC {name: 'F10'}),
                                                      (F11:TypeC {name: 'F11'}),
                                                      (F12:TypeC {name: 'F12'}),
                                                      (F13:TypeC {name: 'F13'}),
                                                      (F14:TypeC {name: 'F14'}),
                                                      (F15:TypeC {name: 'F15'}),
                                                      (G1:TypeC {name: 'G1'}),
                                                      (G2:TypeC {name: 'G2'}),
                                                      (G3:TypeC {name: 'G3'}),
                                                      (G4:TypeC {name: 'G4'}),
                                                      (G5:TypeC {name: 'G5'}),
                                                      (G6:TypeC {name: 'G6'}),
                                                      (G7:TypeC {name: 'G7'}),
                                                      (G8:TypeC {name: 'G8'}),
                                                      (G9:TypeC {name: 'G9'}),
                                                      (G10:TypeC {name: 'G10'}),
                                                      (G11:TypeC {name: 'G11'}),
                                                      (G12:TypeC {name: 'G12'}),
                                                      (G13:TypeC {name: 'G13'}),
                                                      (G14:TypeC {name: 'G14'}),
                                                      (G15:TypeC {name: 'G15'}),
                                                      (G16:TypeC {name: 'G16'}),
                                                      (G17:TypeC {name: 'G17'}),
                                                      (H:TypeC {name: 'H'}),
                                                     \s
                                                      // Create relationships
                                                      (A)-[:BASE_REL]->(B),
                                                      (A)-[:BASE_REL]->(D),
                                                      (B)-[:BASE_REL]->(C),
                                                      (B)-[:BASE_REL]->(E),
                                                      (C)-[:BASE_REL]->(G1),
                                                      (C)-[:BASE_REL]->(G2),
                                                      (C)-[:BASE_REL]->(G3),
                                                      (C)-[:BASE_REL]->(G4),
                                                      (C)-[:BASE_REL]->(G5),
                                                      (C)-[:BASE_REL]->(G6),
                                                      (C)-[:BASE_REL]->(G7),
                                                      (C)-[:BASE_REL]->(G8),
                                                      (C)-[:BASE_REL]->(G9),
                                                      (C)-[:BASE_REL]->(G10),
                                                      (C)-[:BASE_REL]->(G11),
                                                      (C)-[:BASE_REL]->(G12),
                                                      (C)-[:BASE_REL]->(G13),
                                                      (C)-[:BASE_REL]->(G14),
                                                      (C)-[:BASE_REL]->(G15),
                                                      (C)-[:BASE_REL]->(G16),
                                                      (C)-[:BASE_REL]->(G17),
                                                      (D)-[:BASE_REL]->(F1),
                                                      (D)-[:BASE_REL]->(F2),
                                                      (D)-[:BASE_REL]->(F3),
                                                      (D)-[:BASE_REL]->(F4),
                                                      (D)-[:BASE_REL]->(F5),
                                                      (D)-[:BASE_REL]->(F6),
                                                      (D)-[:BASE_REL]->(F7),
                                                      (D)-[:BASE_REL]->(F8),
                                                      (D)-[:BASE_REL]->(F9),
                                                      (D)-[:BASE_REL]->(F10),
                                                      (D)-[:BASE_REL]->(F11),
                                                      (D)-[:BASE_REL]->(F12),
                                                      (D)-[:BASE_REL]->(F13),
                                                      (D)-[:BASE_REL]->(F14),
                                                      (D)-[:BASE_REL]->(F15),
                                                      (E)-[:BASE_REL]->(H);""";
    }
}
